#ifndef METEOR_MAYHEM_CONFIG_H
#define METEOR_MAYHEM_CONFIG_H

#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720

#define MAX_PROJECTILES 512
#define MAX_ASTEROIDS 128
#define MAX_ALIENS 24
#define MAX_ALIEN_PROJECTILES 128

#define STARTING_LIVES 3
#define GAMEPLAY_SCALE 1.5f
#define SHIELD_MAX_CHARGE 100.0f
#define SHIELD_CHARGE_PER_ALIEN 35.0f
#define SHIELD_DURATION 8.0f
#define SHIELD_END_INVINCIBILITY 1.25f
#define SHIELD_SCORE_MULTIPLIER 1.5f

#define STATS_FILE "meteor_stats.dat"
#define SETTINGS_FILE "meteor_settings.dat"

#endif
